name: edusphere
description: "A Flutter Education App"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  # A package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.13.1
  # Customize Flutter's default white native splash screen
  flutter_native_splash: ^2.4.1
  # A flutter plugin for adapting screen and font size
  flutter_screenutil: ^5.9.3


flutter_launcher_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/images/icon/app_icon.jpg"
  min_sdk_android: 21 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf


flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets.dart
  field_prefix: